[package]
name = "sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
rstest = "0.26.1"
reqwest = { version = "0.12", features = ["json"] }
serde = {version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"